// <auto-generated />
namespace QTec.Hrms.DataTier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class Releationship_removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Releationship_removed));
        
        string IMigrationMetadata.Id
        {
            get { return "201311130755401_Releationship_removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
